version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nextjs
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus   # mount direktori, aman & tidak error
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    depends_on:
      - nextjs

networks:
  monitoring:
    driver: bridge
